[package]
name = "smbus-request-parser"
version = "0.2.0"
authors = ["Rafael Bachmann <rafael.bachmann.93@gmail.com>"]
description = "Parse SMBus requests. Register functions to call for each type of write/read request. Agnostic regarding polling, irq, dma usage."
readme = "README.md"
license = "MIT"
repository = "https://github.com/barafael/smbus-request-parser-rs"
edition = "2021"
keywords = ["smbus", "i2c"]
categories = ["embedded"]
